resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:449210b78b12c6f1d85ff459b1b3d7ec4921b68e1879faf082bb4d4d326393d8
  name: operator
  newName: registry.redhat.io/openshift-builds/openshift-builds-rhel9-operator
