apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: source-to-image-java-build
spec:
  description: A sample Build using source-to-image BuildStrategy with java builder image
  snippet: false
  targetResource:
    apiVersion: shipwright.io/v1beta1
    kind: Build
  title: Source-to-Image Java Build
  yaml: |
    apiVersion: shipwright.io/v1beta1
    kind: Build
    metadata:
      name: s2i-java-build
    spec:
      source: 
        type: Git
        git:
          url: https://github.com/monodot/simple-camel-spring-boot-app
      strategy: 
        name: source-to-image
        kind: ClusterBuildStrategy
      paramValues: 
      - name: builder-image
        value: quay.io/myriad/fabric8-s2i-java:latest-java11
      output:
        image: image-registry.openshift-image-registry.svc:5000/namespace/s2i-java-example
